defaults:
  - /defaults/trainer/default@_here_ #inherit serotiny's trainer config
  - callbacks: default

_target_: pytorch_lightning.Trainer
max_epochs:
gpus:
enable_checkpointing: True
default_root_dir: ${output_root}