_target_: ch5_attempt1.model.Classifier
x_label: image
y_label: class
network:
  _target_: serotiny.networks.basic_cnn.BasicCNN
  in_channels: 1
  output_dim: 2
  input_dims: [248,381]
  hidden_channels: [2, 4, 8]
  max_pool_layers: [0, 1, 2]
  non_linearity:
    _target_: torch.nn.ReLU
  skip_connections: True
  mode: '2d'
loss:
  _target_: torch.nn.CrossEntropyLoss